from pptx import Presentation
from pptx.util import Inches, Pt, Emu
from pptx.dml.color import RGBColor
from pptx.enum.text import PP_ALIGN
import os


# ── Design Tokens ──────────────────────────────────────────────
BG_COLOR        = RGBColor(0x0F, 0x17, 0x2A)   # deep navy
ACCENT_COLOR    = RGBColor(0x6C, 0x63, 0xFF)   # electric violet
TITLE_COLOR     = RGBColor(0xFF, 0xFF, 0xFF)   # white
BULLET_COLOR    = RGBColor(0xCC, 0xCC, 0xDD)   # soft lavender-white
SLIDE_W         = Inches(13.33)
SLIDE_H         = Inches(7.5)


def hex_to_rgb(hex_color: str) -> RGBColor:
    h = hex_color.lstrip("#")
    return RGBColor(int(h[0:2], 16), int(h[2:4], 16), int(h[4:6], 16))


def set_bg(slide, prs):
    """Fill slide background with solid color."""
    fill = slide.background.fill
    fill.solid()
    fill.fore_color.rgb = BG_COLOR


def add_title_slide(prs: Presentation, title: str, subtitle: str = ""):
    """Create a branded cover slide."""
    slide_layout = prs.slide_layouts[6]  # blank
    slide = prs.slides.add_slide(slide_layout)
    set_bg(slide, prs)

    # Accent bar on left
    bar = slide.shapes.add_shape(
        1,  # MSO_SHAPE_TYPE.RECTANGLE
        Inches(0), Inches(0),
        Inches(0.18), SLIDE_H
    )
    bar.fill.solid()
    bar.fill.fore_color.rgb = ACCENT_COLOR
    bar.line.fill.background()

    # Title text box
    txBox = slide.shapes.add_textbox(Inches(0.5), Inches(2.5), Inches(12), Inches(1.8))
    tf = txBox.text_frame
    tf.word_wrap = True

    p = tf.paragraphs[0]
    p.text = title
    p.font.size = Pt(40)
    p.font.bold = True
    p.font.color.rgb = TITLE_COLOR
    p.font.name = "Calibri"

    if subtitle:
        from pptx.util import Pt
        p2 = tf.add_paragraph()
        p2.text = subtitle
        p2.font.size = Pt(18)
        p2.font.color.rgb = RGBColor(0x99, 0x99, 0xBB)
        p2.font.name = "Calibri"
        p2.space_before = Pt(12)

    return slide


def add_content_slide(prs: Presentation, title: str, bullets: list[str], page_num: int):
    """Create a content slide with title and bullet points."""
    slide_layout = prs.slide_layouts[6]  # blank
    slide = prs.slides.add_slide(slide_layout)
    set_bg(slide, prs)

    # Top accent bar
    bar = slide.shapes.add_shape(
        1,
        Inches(0), Inches(0),
        SLIDE_W, Inches(0.08)
    )
    bar.fill.solid()
    bar.fill.fore_color.rgb = ACCENT_COLOR
    bar.line.fill.background()

    # Slide number (top right)
    num_box = slide.shapes.add_textbox(Inches(11.8), Inches(0.15), Inches(1.3), Inches(0.4))
    num_tf = num_box.text_frame
    num_p = num_tf.paragraphs[0]
    num_p.text = str(page_num)
    num_p.font.size = Pt(11)
    num_p.font.color.rgb = RGBColor(0x66, 0x66, 0x88)
    num_p.alignment = PP_ALIGN.RIGHT

    # Title
    title_box = slide.shapes.add_textbox(Inches(0.6), Inches(0.3), Inches(11.5), Inches(1.1))
    title_tf = title_box.text_frame
    title_p = title_tf.paragraphs[0]
    title_p.text = title
    title_p.font.size = Pt(28)
    title_p.font.bold = True
    title_p.font.color.rgb = TITLE_COLOR
    title_p.font.name = "Calibri"

    # Divider line
    line = slide.shapes.add_shape(
        1,
        Inches(0.6), Inches(1.35),
        Inches(11.5), Inches(0.03)
    )
    line.fill.solid()
    line.fill.fore_color.rgb = ACCENT_COLOR
    line.line.fill.background()

    # Bullets
    bullet_box = slide.shapes.add_textbox(Inches(0.7), Inches(1.6), Inches(11.5), Inches(5.5))
    bullet_tf = bullet_box.text_frame
    bullet_tf.word_wrap = True

    for i, bullet_text in enumerate(bullets):
        p = bullet_tf.paragraphs[0] if i == 0 else bullet_tf.add_paragraph()
        p.text = f"  {bullet_text}"
        p.font.size = Pt(18)
        p.font.color.rgb = BULLET_COLOR
        p.font.name = "Calibri"
        p.space_before = Pt(10)

        # Add colored bullet dot via run prefix
        run = p.runs[0] if p.runs else p.add_run()
        run.font.color.rgb = BULLET_COLOR

    return slide


def build_pptx(slides_data: list[dict], output_path: str, presentation_title: str = "Presentation"):
    """
    Build a complete .pptx from slides data.
    slides_data: list of {"page": int, "title": str, "bullets": [str]}
    """
    prs = Presentation()
    prs.slide_width  = SLIDE_W
    prs.slide_height = SLIDE_H

    # Cover slide
    add_title_slide(prs, presentation_title, f"{len(slides_data)} slides generated by AI")

    # Content slides
    for i, slide_data in enumerate(slides_data):
        add_content_slide(
            prs,
            title=slide_data.get("title", f"Slide {i+1}"),
            bullets=slide_data.get("bullets", []),
            page_num=i + 1
        )

    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    prs.save(output_path)
    return output_path